# Generated by Django 4.1.4 on 2023-01-30 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_history_options_history_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vip',
            name='update_at',
        ),
    ]
